### ISSUE TITLE
Error: failed to load base spec from <base> with error converting YAML to JSON: yaml: unmarshal errors

### ISSUE THREAD

**Issue by mwithi** [oasdiff/oasdiff-action#21]
Despite locally it works perfectly with .deb from https://github.com/Tufin/oasdiff/releases/tag/v1.9.6 and same `base` and `rev` files, in GitHub Action I get:

```
Error: failed to load base spec from "openapi/oh.yaml" with error converting YAML to JSON: yaml: unmarshal errors:
  line 7991: mapping key "empty" already defined at line 7980
  line 8048: mapping key "empty" already defined at line 8037
  line 8107: mapping key "empty" already defined at line 8096
  line 8159: mapping key "empty" already defined at line 8148
  line 8216: mapping key "empty" already defined at line 8205
  line 8287: mapping key "empty" already defined at line 8276
  line 8344: mapping key "empty" already defined at line 8333
```
https://github.com/mwithi/openhospital-api/actions/runs/6936878852/job/18869869828#step:12:15

base: [oh.yaml.txt](https://github.com/oasdiff/oasdiff-action/files/13420175/oh_base.yaml.txt) ([link](https://github.com/mwithi/openhospital-api/actions/runs/6936878852/job/18869869828#step:11:91))
rev: [oh_rev.yaml.txt](https://github.com/oasdiff/oasdiff-action/files/13420176/oh_rev.yaml.txt) ([link](https://github.com/mwithi/openhospital-api/blob/develop/openapi/oh.yaml))

**Note**: I'm using my fork inspired by #19, but the error is the same with `oasdiff/oasdiff-action/breaking@main`

**Comment by effoeffi** [comment]
> Despite locally it works perfectly with .deb from https://github.com/Tufin/oasdiff/releases/tag/v1.9.6 and same `base` and `rev` files, in GitHub Action I get:
> 
> ```
> Error: failed to load base spec from "openapi/oh.yaml" with error converting YAML to JSON: yaml: unmarshal errors:
>   line 7991: mapping key "empty" already defined at line 7980
>   line 8048: mapping key "empty" already defined at line 8037
>   line 8107: mapping key "empty" already defined at line 8096
>   line 8159: mapping key "empty" already defined at line 8148
>   line 8216: mapping key "empty" already defined at line 8205
>   line 8287: mapping key "empty" already defined at line 8276
>   line 8344: mapping key "empty" already defined at line 8333
> ```
> 
> https://github.com/mwithi/openhospital-api/actions/runs/6936878852/job/18869869828#step:12:15
> 
> base: [oh.yaml.txt](https://github.com/oasdiff/oasdiff-action/files/13420175/oh_base.yaml.txt) ([link](https://github.com/mwithi/openhospital-api/actions/runs/6936878852/job/18869869828#step:11:91)) rev: [oh_rev.yaml.txt](https://github.com/oasdiff/oasdiff-action/files/13420176/oh_rev.yaml.txt) ([link](https://github.com/mwithi/openhospital-api/blob/develop/openapi/oh.yaml))
> 
> **Note**: I'm using my fork inspired by #19, but the error is the same with `oasdiff/oasdiff-action/breaking@main`

It is working for me, see:
1. running action: https://github.com/oasdiff/oasdiff-action/actions/runs/6948164192
2. PR including your specs: https://github.com/oasdiff/oasdiff-action/pull/22

<img width="1319" alt="image" src="https://github.com/oasdiff/oasdiff-action/assets/7524834/0a9e6428-ddfb-46fe-ad38-f812ccb6a0b1">

**Comment by mwithi** [comment]
Thank you @effoeffi, any hint? maybe my yamel is wrong? Do you see something not correct?
https://github.com/mwithi/openhospital-api/blob/test-OH2-246_base/.github/workflows/openapi.yml

Thanks

**Comment by effoeffi** [comment]
> Thank you @effoeffi, any hint? maybe my yamel is wrong? Do you see something not correct? https://github.com/mwithi/openhospital-api/blob/test-OH2-246_base/.github/workflows/openapi.yml
> 
> Thanks

I don't see anything wrong.
Maybe there is a diff in your fork? Why do you prefer to work with a fork?

**Comment by reuvenharrison** [comment]
Hi @mwithi,
I noticed that the link to `base` above downloads [oh.yaml.txt](https://github.com/oasdiff/oasdiff-action/files/13420175/oh_base.yaml.txt) while your [GitHub action output](https://github.com/mwithi/openhospital-api/actions/runs/6936878852/job/18869869828#step:12:15) shows that you are comparing `openapi/oh.yaml` (not .txt).
Perhaps this is the problem?

**Comment by mwithi** [comment]
> Hi @mwithi, I noticed that the link to `base` above downloads [oh.yaml.txt](https://github.com/oasdiff/oasdiff-action/files/13420175/oh_base.yaml.txt) while your [GitHub action output](https://github.com/mwithi/openhospital-api/actions/runs/6936878852/job/18869869828#step:12:15) shows that you are comparing `openapi/oh.yaml` (not .txt). Perhaps this is the problem?

@reuvenharrison no, I've reneamed them .txt because otherwise GitHub won't accept the upload

**Comment by mwithi** [comment]
> > Thank you @effoeffi, any hint? maybe my yamel is wrong? Do you see something not correct? https://github.com/mwithi/openhospital-api/blob/test-OH2-246_base/.github/workflows/openapi.yml
> > Thanks
> 
> I did not check your fork. May I ask, why do you prefer to work with a fork?

@effoeffi because I'm testing contributions from other devs

**Comment by mwithi** [comment]
@effoeffi Or do you refer to my oasdiff fork? As I put in the **Note**: I'm using my fork inspired by https://github.com/oasdiff/oasdiff-action/pull/19, but the error is the same with `oasdiff/oasdiff-action/breaking@main`. Reverted to oasdiff now, with same result.

**Comment by mwithi** [comment]
@effoeffi Are this services still working? https://www.oasdiff.com/diff-as-a-service

**Comment by mwithi** [comment]
@reuvenharrison should I open this issue in https://github.com/Tufin/oasdiff ?

**Comment by mwithi** [comment]
Sorry my mistake: it turned out that the problem was in the base file initially provided in the repo and not in the generated revision which was really ok indeed. **Lesson learnt: to always revise assumptions! 😅**

Thank you all for the support and congrats for this great tool! 👏

**Comment by effoeffi** [comment]
> @effoeffi Are these services still working? https://www.oasdiff.com/diff-as-a-service

@mwithi Yes it is working. Please, join our community in slack, we will continue the conversation in there
https://join.slack.com/t/oasdiff/shared_invite/zt-27l6y20xw-hcwzpcA7v8FobfRogTCgtg
