### ISSUE TITLE
breaking output only shows one line

### ISSUE THREAD

**Issue by joaoluiznaufel** [oasdiff/oasdiff-action#34]
The output of breaking its showing only one line. 

**This is the result**
![image](https://github.com/oasdiff/oasdiff-action/assets/1915340/a8844d59-967f-4418-85b2-f68aa72ee30d)

**The desired result**
![image](https://github.com/oasdiff/oasdiff-action/assets/1915340/2fa5b436-ef0d-47cd-a7f7-30258e39b121)

**Comment by effoeffi** [comment]
Right, currently github action output written into 3 places:
1. Output log.
2. Annotation as part of summary summary (see [here](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions)).
3. *Summary* as a step output (like you mentioned).

**Comment by joaoluiznaufel** [comment]
Ok, I kind of solved removing the:
`| head-n 1`
and here you can see that it will delivery only the first line, but I want all.
Thanks for the fast interaction.
