### ISSUE TITLE
Diff action output has only one line

### ISSUE THREAD

**Issue by WiktorKryzia** [oasdiff/oasdiff-action#35]
In the last commit (349892f7a08141d928989568092d8716a9b1e094) the output of the "oasdiff diff" was limited for unknown reasons with the command: ` | head -n 1`.

As a result, only the first line of the diff can be displayed, e.g.:
`### New Endpoints: None`

**Comment by effoeffi** [comment]
Please, review the fix: https://github.com/oasdiff/oasdiff-action/pull/36/files
