### ISSUE TITLE
breaking output limited to one line 

### ISSUE THREAD

**Issue by ssukienn** [oasdiff/oasdiff-action#42]
I've seen https://github.com/oasdiff/oasdiff-action/issues/35 but still, what is the purpose of that head? 

Breaking output is different than diff or changelog. I would like to use that output in the PR comment. Could this be changed?

**Comment by effoeffi** [comment]
The idea is to include a summary in the PR and provide links to the report, as well as to the diff and changelog. The report can contain hundreds of lines. We initiated a discussion about this [here](https://github.com/Tufin/oasdiff/discussions/453). Please feel free to add your feedback.

**Comment by ssukienn** [comment]
Thanks for the input. 

What's wrong with output having hundreds of lines? If I made that many breaking changes I would like to inspect those and text format in one place might be more convieniet at times (than annotations). And I've seen you already scoping it for that 1mb gh limit in all cases. 

Currently `diff` and `changelog` have no limits but `breaking` has it out of the blue, for the same `GITHUB_OUTPUT`. 

My use case is to present the breaking change inspection in the spoiler format in the GitHub comment. Annotations are nice but my use case is to present text format in a comment. This is similar to Spacelift integration commenting its terraform plans on PR. 

I understand you want to revamp and enchance how action would work in general though this is the problem I'm facing on the current action version.

**Comment by effoeffi** [comment]
@ssukienn could you please take a look at this [PR](https://github.com/oasdiff/oasdiff-action/pull/44) and let me know if it resolves your issue?
