### ISSUE TITLE
Getting an error 'Error: Unable to process file command 'output' successfully.' when running oasdiff/oasdiff-action/diff@main from main.

### ISSUE THREAD

**Issue by lioramazor** [oasdiff/oasdiff-action#50]
Hi,

When we are running the diff check from the main branch we are getting the errors below:
`10running oasdiff diff base: specs/original-spec.yaml, revision: specs/modified-spec.yaml, format: text, fail_on_diff: true, include_path_params: false, exclude_elements: , composed: false, output_to_file:
11flags:  --format text --fail-on-diff
12Error: Unable to process file command 'output' successfully.
13Error: Invalid value. Matching delimiter not found 'a48a4f97a1a9457eb4dd8bb5332a6f3c'`

To fix it we set the version **v.0.0.16** and it worked:
`oasdiff/oasdiff-action/diff@v0.0.16` from `oasdiff/oasdiff-action/diff@main`

Let me know if additional details are needed.
Thanks,

**Comment by effoeffi** [comment]
@lioramazor, thank you for your assistance!
Could you please help by writing a test that reproduces the issue?

**Comment by lioramazor** [comment]
@effoeffi of course.
We are running oasdiff in our gated PR using Github action.

The steps:

1. Change some values in the openapi.yaml/json file in a side branch and create a pull request to the main branch.
2. The pull request is running the test from `oasdiff/oasdiff-action/diff@main` using the following command:
`      - name: Running OpenAPI Spec diff action
          id: test_ete
          uses: oasdiff/oasdiff-action/diff@main
          with:
            base: 'specs/original-spec.yaml' //main
            revision: 'specs/modified-spec.yaml' //branch
          fail-on-diff: true`
And then it failed with the error `Error: Unable to process file command 'output' successfully.`

Let me know if additional information is needed.
Thanks,

**Comment by effoeffi** [comment]
@lioramazor take a look in our tests in [here](https://github.com/oasdiff/oasdiff-action/blob/main/.github/workflows/test.yaml)
Can you add a similar test that reproduces the issue?

**Comment by lioramazor** [comment]
@effoeffi sharing the test:

`
name: API Breaking Changes
on:
  pull_request:

jobs:
  build-oas-artefacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install required tools
        run: |
          npm install speccy -g
          npm install -g @openapitools/openapi-generator-cli@1.0.10-4.2.3
        env:
          CURRENT_BRANCH: ${{ github.head_ref }}
          TARGET_BRANCH: ${{ github.base_ref }}

      - name: Clone repository in branch ${{ env.TARGET_BRANCH }}
        uses: actions/checkout@v2
        with:
          path: 'A'
          ref: ${{ github.base_ref }}

      - name: Clone repository in branch ${{ env.CURRENT_BRANCH }}
        uses: actions/checkout@v2
        with:
          path: 'B'

      - name: Check if OAS from ${{ env.CURRENT_BRANCH }} is valid
        run: |
          npx openapi-generator validate -i B/openapi/openapi.yaml

      - name: Check if OAS from ${{ env.TARGET_BRANCH }} is valid
        run: |
          npx openapi-generator validate -i A/openapi/openapi.yaml

      - name: Build OAS specifications
        run: |
          npx speccy resolve A/openapi/openapi.yaml -o original-spec.yaml
          npx speccy resolve B/openapi/openapi.yaml -o modified-spec.yaml

      - name: Upload single OAS file from ${{ env.TARGET_BRANCH }}
        uses: actions/upload-artifact@v1
        with:
          name: original-spec.yaml
          path: original-spec.yaml

      - name: Upload single OAS file from ${{ env.CURRENT_BRANCH }}
        uses: actions/upload-artifact@v1
        with:
          name: modified-spec.yaml
          path: modified-spec.yaml

  build-report:
    needs: build-oas-artefacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: Download OAS file from SOURCE branch
        uses: actions/download-artifact@v1
        with:
          name: original-spec.yaml
          path: specs/

      - name: Download OAS file from TARGET branch
        uses: actions/download-artifact@v1
        with:
          name: modified-spec.yaml
          path: specs/

      - name: Restore permissions
        run: |
          chmod -R 600 $(pwd)/specs/original-spec.yaml
          chmod -R 600 $(pwd)/specs/modified-spec.yaml

      - name: Print original-spec
        run: cat $(pwd)/specs/original-spec.yaml

      - name: Print modified-spec
        run: echo $(pwd) && cat $(pwd)/specs/modified-spec.yaml

      - name: Running OpenAPI Spec diff action
        id: test_ete
        uses: oasdiff/oasdiff-action/diff@v0.0.16
        with:
          base: 'specs/original-spec.yaml'
          revision: 'specs/modified-spec.yaml'
          fail-on-diff: true
`

**Comment by effoeffi** [comment]
@lioramazor, what I need is to reproduce the issue. Unfortunately, I cannot do so with the example you sent. It's evident that our tests do not reproduce the issue. Could you open a PR with a test, or share a repository that reproduces it?

**Comment by lioramazor** [comment]
@effoeffi We found the issue, we set the format value to 'text':
`      - name: Running OpenAPI Spec diff action
            id: test_ete
            uses: oasdiff/oasdiff-action/diff@main
            with:
              base: 'specs/original-spec.yaml'
              revision: 'specs/modified-spec.yaml'
              **format: 'text'**
              fail-on-diff: true`
It worked when we ran it without  `format: 'text'`.
