### ISSUE TITLE
Update the README with realistic examples

### ISSUE THREAD

**Issue by clintonb** [oasdiff/oasdiff-action#59]
I would expect this action to be used on a pull request. Update the examples for that use case. Demonstrate how to compare data from a base branch to the working branch. This will make it easier for folks to use the action without the guess work around making it functional.

**Comment by effoeffi** [comment]
Have you had a chance to check the [tests](https://github.com/oasdiff/oasdiff-action/blob/main/.github/workflows/test.yaml)? They include examples demonstrating how to use the action for various use cases. We also welcome PRs if there's something you'd like to add or improve.

**Comment by fraser-langton** [comment]
docs are sorely needed for Use PR diff as base and revision #55 - I am pulling my hair out, I would assume this is the main use case of a github action?
